version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meme_generator
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=meme_generator
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data: